
SELECT
	DATEADD(DD, Q.nn, '01-JAN-2000') 
FROM
	(
	SELECT
		D1.n + D2.n * 10 + D3.n * 100 + D4.n * 1000 AS nn
	FROM
		(SELECT 0 n UNION SELECT 1  UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) D1
		CROSS JOIN (SELECT 0 n UNION SELECT 1  UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) D2
		CROSS JOIN (SELECT 0 n UNION SELECT 1  UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) D3
		CROSS JOIN (SELECT 0 n UNION SELECT 1  UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9) D4
	) Q
ORDER BY
	1
